version: '3'

services:

  abp_host:
    image: abp/mvc
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "Server=bush-rds.maychudns.net,1441; Database=trochoixua_io_vn_db; User=trochoixua_io_vn; Password=#zsuuoP@Ah205Cgd; TrustServerCertificate=True;"
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44312:80"
    volumes:
      - "./Mvc-Logs:/app/App_Data/Logs"
    restart: always
