# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     # Step 0: Set User
    - name: Set User
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    # Step 1: Checkout code from main branch
    - name: Checkout source cod
      uses: actions/checkout@v4
      with:
        ref: main  # Pull từ nhánh main
        
    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # Step 3: Restore dependencies    
    - name: Restore dependencies
      run: dotnet restore
      
    # Step 3: Libman restore
    #- name: Libman restore
    #  run: |
    #    dotnet tool install -g Microsoft.Web.LibraryManager.Cli
    #    libman restore src/GameXuaVN.Web.Mvc/libman.json
      
    # Step 4: Clean 
    - name: Clean
      run: |
        # Xóa thư mục publish cũ nếu có
        if [ -d "./publish" ]; then
          echo "Cleaning old publish data..."
          rm -rf ./publish
        fi

    # Step 4: Build project
    - name: Build
      #run: dotnet build --no-restore
      run: |
        # Danh sách các file .csproj cần build và publish
        PROJECT="src/GameXuaVN.Web.Mvc/GameXuaVN.Web.Mvc.csproj"
        
        echo "Building $PROJECT"
        dotnet build "$PROJECT" --configuration Release
        
        echo "Publishing $PROJECT"
        dotnet publish "$PROJECT" --configuration Release --output ./publish
        

     # Step 6: Upload artifact (thư mục publish)
    - name: Upload publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-artifact
        path: ./publish  # Đường dẫn đến thư mục chứa các file đã publish
        
    # Step 7: Setup SSH for push to deploy branch
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 
        
    # Step 7: Checkout release branch
    - name: Checkout Deploy branch
      run: |
        git fetch origin
        git branch -r  # Kiểm tra các nhánh từ remote
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b deploy origin/deploy || git checkout deploy || git checkout -b deploy

    # Step 8: Clone deploy branch
    - name: Clone deploy branch
      run: |
        git clone --depth 1 --single-branch -b deploy git@github.com:fx350ms/gamexua.io.vn.git deploy
        mv deploy/.git deploy-.git
        rm -rf deploy
        mkdir deploy
        mv deploy-.git deploy/.git

    # Step 9: Copy published files to deploy branch
    - name: Copy published files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir -p ./deploy
        cp -R ./publish/* ./deploy
        cd deploy
        git init
        if git remote | grep origin; then
          git remote set-url origin git@github.com:fx350ms/gamexua.io.vn.git
        else
          git remote add origin git@github.com:fx350ms/gamexua.io.vn.git
        fi
        git add .
        git diff --staged --quiet || git commit -m "Update Artifacts"
        git push origin deploy --force
        
    # Step 10: Push changes to deploy branch
    #- name: Push changes to deploy branch
     # run: |
     #   cd ./deploy
     #   git push deploy --force
